name: .NET CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'release/*'
  pull_request:
    branches:
      - master

jobs:
  deploy:
      name: Build, test and publish on release
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'

        - run: dotnet test 

        - name: dotnet pack
          run: dotnet pack **/Orleans.Serialization.NodaTime.csproj

        - name: nuget push
          if: startsWith(github.ref, 'refs/tags/release/')
          run: nuget push **/Orleans.Serialization.NodaTime*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

